Repository ML-name/project, pull requests merged in 2025-04, with the labels that each got.

#43 Scraping/inline feedback
  notebook.ipynb
  notebook.py
  tropos/__init__.py
  tropos/preprocess_docx/comments.py
Labels: enhancement

#46 Scraping/all together
  data/processed/assignment/student_submissions/Student_1/final.json
  data/processed/assignment/student_submissions/Student_1/part1.json
  data/processed/assignment/student_submissions/Student_1/part2.json
  data/processed/assignment/student_submissions/Student_1/part3.json
  notebook.ipynb
  tropos/__init__.py
  tropos/preprocess_docx/WIP_scraper1.py
Labels: documentation

#50 fixed notebook, it was broken after merge conflict resolution.
  notebook.ipynb
  notebook.py
Labels: fix

#54 Prompting/api additions
  README.md
  notebook.ipynb
  notebook.py
  tropos/__init__.py
  tropos/feedback_engine.py
  tropos/feedback_formatting.py
  tropos/models/__init__.py
  tropos/models/claude.py
  tropos/models/deepseek.py
  tropos/models/gemini.py
  tropos/models/llama.py
  tropos/models/model_router.py
  tropos/models/prompt_builder.py
Labels: enhancement

#59 fixed llama again???
  tropos/models/llama.py
  tropos/models/prompt_builder.py
Labels: bug
